<?php
/**
 * Created by PhpStorm.
 * User: laozhou
 * Date: 2019/8/31
 * Time: 00:43
 */

namespace app\controller\api\base;

use App;

class baseAction extends \app\controller\base\baseAction
{
	protected $csrfValidate = false;
	
	protected $accessToken = '';
	
	public function init()
	{
		$this->accessToken = $this->param('access_token');
	}
	
	public function json($data, $encode = false)
	{
		return parent::json($data, $encode); // TODO: Change the autogenerated stub
	}
	
	public function errorJson($message) {
		return $this->json(['error'=>-1,'message'=>$message]);
	}
	
	public function successJson($data = []) {
		return $this->json(['error'=>0, 'message'=>'OK', 'data'=>$data]);
	}
	
	protected function getUserByAccessToken() {
		$user = App::$model->user(['access_token'=>$this->accessToken]);
		if ($user->exist()) {
			return $user;
		}
		return false;
	}
	
}